=== michael-pucci/Progetto-Codifca/PROGETTO CODIFICA/tei_all.dtd
<!ELEMENT TEI ( teiHeader, facsimile, text ) >
<!ATTLIST TEI xmlns CDATA #REQUIRED >

<!ELEMENT ab ( #PCDATA | abbr | add | choice | del | emph | expan | lb | mentioned | term )* >
<!ATTLIST ab corresp CDATA #IMPLIED >
<!ATTLIST ab n ( 1 | 10 | 11 | 12 | 13 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >
<!ATTLIST ab type ( parte ) #IMPLIED >
<!ATTLIST ab xml:id ID #IMPLIED >
<!ATTLIST ab xml:lang ( it ) #IMPLIED >

<!ELEMENT abbr ( #PCDATA | am )* >

<!ELEMENT acquisition ( p ) >

<!ELEMENT add ( #PCDATA | choice | term )* >
<!ATTLIST add place ( above | below | inline | top ) #REQUIRED >

<!ELEMENT address ( postCode, name ) >

<!ELEMENT am ( #PCDATA ) >

<!ELEMENT author ( #PCDATA | forename | surname )* >
<!ATTLIST author ref CDATA #IMPLIED >
<!ATTLIST author xml:id NMTOKEN #IMPLIED >

<!ELEMENT availability ( p ) >

<!ELEMENT back ( list, listPerson, listPlace, listBibl ) >

<!ELEMENT bibl ( author | date | pubPlace | publisher | title )* >
<!ATTLIST bibl source CDATA #IMPLIED >
<!ATTLIST bibl xml:id NMTOKEN #REQUIRED >
<!ATTLIST bibl xml:lang NMTOKEN #IMPLIED >

<!ELEMENT body ( div+ ) >

<!ELEMENT byline ( #PCDATA | docAuthor )* >

<!ELEMENT channel EMPTY >
<!ATTLIST channel mode NMTOKEN #REQUIRED >

<!ELEMENT choice ( corr | orig | reg | sic )* >

<!ELEMENT constitution EMPTY >
<!ATTLIST constitution type NMTOKEN #REQUIRED >

<!ELEMENT corr ( #PCDATA ) >

<!ELEMENT country ( #PCDATA ) >

<!ELEMENT date ( #PCDATA ) >
<!ATTLIST date when NMTOKEN #IMPLIED >

<!ELEMENT del ( #PCDATA | gap )* >
<!ATTLIST del rend ( overstrike | overtyped | ovestrike ) #REQUIRED >

<!ELEMENT derivation EMPTY >
<!ATTLIST derivation type NMTOKEN #REQUIRED >

<!ELEMENT div ( ab | pb )* >
<!ATTLIST div n NMTOKEN #REQUIRED >
<!ATTLIST div type NMTOKEN #REQUIRED >

<!ELEMENT docAuthor ( #PCDATA ) >

<!ELEMENT docDate ( #PCDATA ) >

<!ELEMENT docImprint ( #PCDATA | docDate )* >

<!ELEMENT domain EMPTY >
<!ATTLIST domain type NMTOKEN #REQUIRED >

<!ELEMENT edition ( #PCDATA | date )* >

<!ELEMENT editionStmt ( edition, editor, respStmt+ ) >

<!ELEMENT editor ( #PCDATA ) >
<!ATTLIST editor resp CDATA #REQUIRED >

<!ELEMENT emph ( #PCDATA | abbr | choice | expan | term )* >
<!ATTLIST emph rend NMTOKEN #FIXED "underline" >

<!ELEMENT encodingDesc ( projectDesc ) >

<!ELEMENT ex ( #PCDATA ) >

<!ELEMENT expan ( #PCDATA | ex )* >

<!ELEMENT extent ( #PCDATA ) >

<!ELEMENT facsimile ( surface+ ) >

<!ELEMENT factuality EMPTY >
<!ATTLIST factuality type NMTOKEN #REQUIRED >

<!ELEMENT fileDesc ( titleStmt, editionStmt, publicationStmt, sourceDesc ) >

<!ELEMENT forename ( #PCDATA ) >

<!ELEMENT gap EMPTY >
<!ATTLIST gap extent NMTOKEN #REQUIRED >
<!ATTLIST gap reason NMTOKEN #FIXED "illegible" >
<!ATTLIST gap unit NMTOKEN #FIXED "chars" >

<!ELEMENT gloss ( #PCDATA ) >
<!ATTLIST gloss source CDATA #REQUIRED >
<!ATTLIST gloss target CDATA #REQUIRED >

<!ELEMENT graphic EMPTY >
<!ATTLIST graphic height NMTOKEN #REQUIRED >
<!ATTLIST graphic url NMTOKEN #REQUIRED >
<!ATTLIST graphic width NMTOKEN #REQUIRED >
<!ATTLIST graphic xml:id NMTOKEN #REQUIRED >

<!ELEMENT handDesc ( p ) >

<!ELEMENT history ( summary, origin, acquisition ) >

<!ELEMENT idno ( #PCDATA ) >

<!ELEMENT interaction EMPTY >
<!ATTLIST interaction active NMTOKEN #REQUIRED >
<!ATTLIST interaction passive NMTOKEN #REQUIRED >
<!ATTLIST interaction type NMTOKEN #REQUIRED >

<!ELEMENT item ( gloss ) >
<!ATTLIST item n NMTOKEN #REQUIRED >

<!ELEMENT label ( term+ ) >

<!ELEMENT langUsage ( language ) >

<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language ident NMTOKEN #REQUIRED >

<!ELEMENT layout ( p ) >
<!ATTLIST layout columns NMTOKEN #REQUIRED >
<!ATTLIST layout ruledLines CDATA #REQUIRED >

<!ELEMENT layoutDesc ( layout ) >

<!ELEMENT lb EMPTY >
<!ATTLIST lb break NMTOKEN #IMPLIED >
<!ATTLIST lb facs CDATA #REQUIRED >
<!ATTLIST lb rend CDATA #IMPLIED >

<!ELEMENT list ( item | label )* >
<!ATTLIST list rend NMTOKEN #REQUIRED >
<!ATTLIST list type NMTOKEN #REQUIRED >

<!ELEMENT listBibl ( bibl+ ) >

<!ELEMENT listPerson ( person ) >

<!ELEMENT listPlace ( place+ ) >

<!ELEMENT material ( #PCDATA ) >

<!ELEMENT mentioned ( #PCDATA | choice | emph )* >
<!ATTLIST mentioned rend NMTOKEN #IMPLIED >
<!ATTLIST mentioned xml:lang NMTOKEN #FIXED "fr" >

<!ELEMENT msContents ( msItem ) >

<!ELEMENT msDesc ( msIdentifier, msContents, physDesc, history ) >

<!ELEMENT msIdentifier ( placeName, repository, idno ) >

<!ELEMENT msItem ( title, byline, textLang, docImprint ) >

<!ELEMENT name ( #PCDATA | country | placeName )* >
<!ATTLIST name type NMTOKEN #IMPLIED >
<!ATTLIST name xml:id NMTOKEN #IMPLIED >

<!ELEMENT objectDesc ( supportDesc, layoutDesc ) >

<!ELEMENT orig ( #PCDATA ) >

<!ELEMENT origin ( p ) >
<!ATTLIST origin notAfter NMTOKEN #REQUIRED >

<!ELEMENT p ( #PCDATA | date | name | persName | placeName )* >

<!ELEMENT pb EMPTY >
<!ATTLIST pb facs CDATA #REQUIRED >
<!ATTLIST pb n NMTOKEN #REQUIRED >

<!ELEMENT persName ( #PCDATA | forename | ref | surname )* >
<!ATTLIST persName ref CDATA #IMPLIED >
<!ATTLIST persName role NMTOKEN #IMPLIED >

<!ELEMENT person ( persName ) >
<!ATTLIST person xml:id NMTOKEN #REQUIRED >

<!ELEMENT physDesc ( objectDesc, handDesc, typeDesc ) >

<!ELEMENT place ( placeName, settlement, country ) >
<!ATTLIST place xml:id NMTOKEN #REQUIRED >

<!ELEMENT placeName ( #PCDATA | region | settlement )* >
<!ATTLIST placeName ref CDATA #IMPLIED >
<!ATTLIST placeName xml:id NMTOKEN #IMPLIED >

<!ELEMENT postCode ( #PCDATA ) >

<!ELEMENT preparedness EMPTY >
<!ATTLIST preparedness type NMTOKEN #REQUIRED >

<!ELEMENT profileDesc ( langUsage, textDesc, settingDesc ) >

<!ELEMENT projectDesc ( p ) >

<!ELEMENT pubPlace ( #PCDATA | placeName )* >
<!ATTLIST pubPlace ref CDATA #IMPLIED >

<!ELEMENT publicationStmt ( publisher, pubPlace, address, availability, date ) >

<!ELEMENT publisher ( #PCDATA ) >

<!ELEMENT purpose EMPTY >
<!ATTLIST purpose degree NMTOKEN #REQUIRED >
<!ATTLIST purpose type NMTOKEN #REQUIRED >

<!ELEMENT ref EMPTY >
<!ATTLIST ref target CDATA #REQUIRED >
<!ATTLIST ref xml:lang NMTOKEN #REQUIRED >

<!ELEMENT reg ( #PCDATA | mentioned )* >

<!ELEMENT region ( #PCDATA ) >
<!ATTLIST region key NMTOKEN #REQUIRED >
<!ATTLIST region type NMTOKEN #REQUIRED >

<!ELEMENT repository ( #PCDATA ) >
<!ATTLIST repository ref CDATA #REQUIRED >
<!ATTLIST repository role NMTOKEN #REQUIRED >

<!ELEMENT resp ( #PCDATA ) >

<!ELEMENT respStmt ( name | resp )* >

<!ELEMENT setting ( name, time ) >

<!ELEMENT settingDesc ( setting ) >

<!ELEMENT settlement ( #PCDATA ) >

<!ELEMENT sic ( #PCDATA ) >

<!ELEMENT sourceDesc ( msDesc ) >

<!ELEMENT summary ( #PCDATA ) >

<!ELEMENT support ( #PCDATA | material )* >

<!ELEMENT supportDesc ( support, extent ) >

<!ELEMENT surface ( graphic, zone*, surface? ) >

<!ELEMENT surname ( #PCDATA ) >

<!ELEMENT teiHeader ( fileDesc, encodingDesc, profileDesc ) >

<!ELEMENT term ( #PCDATA | add | emph | expan )* >
<!ATTLIST term ref CDATA #IMPLIED >
<!ATTLIST term xml:id ID #IMPLIED >
<!ATTLIST term xml:lang ( fr | it ) #IMPLIED >

<!ELEMENT text ( body, back ) >
<!ATTLIST text subtype NMTOKEN #REQUIRED >
<!ATTLIST text xml:id NMTOKEN #REQUIRED >
<!ATTLIST text xml:lang NMTOKEN #REQUIRED >

<!ELEMENT textDesc ( channel, constitution, derivation, domain, factuality, interaction, preparedness, purpose ) >

<!ELEMENT textLang ( #PCDATA ) >
<!ATTLIST textLang mainLang NMTOKEN #REQUIRED >

<!ELEMENT time ( date ) >

<!ELEMENT title ( #PCDATA | persName )* >
<!ATTLIST title type NMTOKEN #IMPLIED >
<!ATTLIST title xml:lang NMTOKEN #IMPLIED >

<!ELEMENT titleStmt ( title+, author, respStmt ) >

<!ELEMENT typeDesc ( p ) >

<!ELEMENT zone EMPTY >
<!ATTLIST zone lrx NMTOKEN #REQUIRED >
<!ATTLIST zone lry NMTOKEN #REQUIRED >
<!ATTLIST zone ulx NMTOKEN #REQUIRED >
<!ATTLIST zone uly NMTOKEN #REQUIRED >
<!ATTLIST zone xml:id ID #IMPLIED >

=== michael-pucci/Progetto-Codifca/PROGETTO CODIFICA/prog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="prog.xsl"?>
<!DOCTYPE TEI SYSTEM "tei_all.dtd">
<TEI
	xmlns="http://www.tei-c.org/ns/1.0">
	<teiHeader>
		<fileDesc>
			<titleStmt>
				<title xml:lang="fr" type="main">Trois premières conférences à l'Universitè</title>
				<title xml:lang="it" type="alt">Le prime tre conferenze all'università</title>
				<author ref="fds">Ferdinand de Saussure</author>
				<respStmt>
					<resp>Traduzione di:</resp>
					<name xml:id="EF">Emanuele Fadda</name>
				</respStmt>
			</titleStmt>
			<editionStmt>
				<edition>Edizione digitale                    
                    
					<date>marzo 2021</date>
				</edition>
				<editor resp="Michael Pucci"> Michael Pucci</editor>
				<respStmt>
					<resp>Edizione francese a cura di:</resp>
					<name>Simon Bouquet</name>
					<name>Rudolf Engler</name>
					<resp>Codificato da:</resp>
					<name xml:id="MP">Michael Pucci</name>
				</respStmt>
				<respStmt>
					<resp>Progetto coordinato da</resp>
					<name xml:id="prof">Angelo Mario Del Grosso</name>
				</respStmt>
			</editionStmt>
			<publicationStmt>
				<publisher>Università di Pisa</publisher>
				<pubPlace>Pisa, PI</pubPlace>
				<address>
					<postCode>56127</postCode>
					<name>Italia</name>
				</address>
				<availability>
					<p>Opera ad accesso libero</p>
				</availability>
				<date when="2021">2021</date>
			</publicationStmt>
			<sourceDesc>
				<msDesc>
					<msIdentifier>
						<placeName>
							<settlement>Ginevra</settlement>
							<region key="CH" type="state">Svizzera</region>
						</placeName>
						<repository ref="https://archives.bge-geneve.ch/ark:/17786/vta01d046d929f231ba" role="library">Biblioteca di Ginevra</repository>
						<idno>BGE Ms.fr.3951/1.1-3</idno>
					</msIdentifier>
					<msContents>
						<msItem>
							<title>Trois premières conférences à l'Universitè</title>
							<byline>di                               
                                
								<docAuthor>Ferdinand De Saussure,</docAuthor>linguista e semiologo svizzero.                            
                            
							</byline>
							<textLang mainLang="fr">Scritto in francese.</textLang>
							<docImprint>Ginevra,
                                
								<docDate>1891</docDate>
							</docImprint>
						</msItem>
					</msContents>
					<physDesc>
						<objectDesc>
							<supportDesc>
								<support>Fogli di 
                                    
									<material>carta </material>
								</support>
								<extent>nello specifico 30 + 15 + 22 pagine, 67 pagine inj totale, più 1 foglietto. </extent>
							</supportDesc>
							<layoutDesc>
								<layout columns="1" ruledLines="20 30">
									<p> Le pagine hanno tra le 20 e le 30 righe, senza considerare le eventuali cancellature, 
                                         aggiunte di elementi esterni, note o correzioni.</p>
								</layout>
							</layoutDesc>
						</objectDesc>
						<handDesc>
							<p>Scritto da una sola mano, ovvero quella dell'autore.</p>
						</handDesc>
						<typeDesc>
							<p>Scritto in caratteri corsivi, non sempre di facile comprensione in quanto si tratta di appunti scritti a mano. 
                            Alcune parole sono sottolineate e altre cancellate.</p>
						</typeDesc>
					</physDesc>
					<history>
						<summary>Questo manoscritto si compone di 3 parti, ognuna corrispondente a una prolusione ginevrina.</summary>
						<origin notAfter="1891">
							<p>Gli appunti vennero scritti da                                
                                
								<persName>Ferdinand De Saussure</persName>
                            e vennero parzialmente presentati durante le prime tre lezioni del corso di 
                            fonetica greca e latina del                                
                                
								<date when="1891-11-06">6</date>,                                
                                
								<date when="1891-11-10"> 10</date>
                            e                               
                                
								<date when="1891-11-13">13 novembre 1891</date> a                                 
                                
								<placeName>Ginevra</placeName>
                            ma probabilmente erano destinati alla pubblicazione di una brochure.                            
                            
							</p>
						</origin>
						<acquisition>
							<p>Il manoscritto originale venne acquisito dalla Biblioteca di                            
                                
								<placeName>Ginevra</placeName>
                            come molti altri archivi dell'autore donati alla biblioteca in diversi lotti da 
                                
								<name type="person">Jacques</name>,
                                
								<name type="person"> Raymond</name>,
                                
								<name type="person"> Madame Bertrand </name>e
                                
								<name type="person"> Claude De Saussure</name>.
                            
							</p>
						</acquisition>
					</history>
				</msDesc>
			</sourceDesc>
		</fileDesc>
		<encodingDesc>
			<projectDesc>
				<p>Il manoscritto originale è stato codificato secondo le specifiche TEI 
				per permettere la consultazione digitale degli appunti di 
                    
					<persName>Ferdinand de Saussure</persName>
				</p>
			</projectDesc>
		</encodingDesc>
		<profileDesc>
			<langUsage>
				<language ident="fr">Francese</language>
			</langUsage>
			<textDesc>
				<channel mode="w" />
				<constitution type="single"/>
				<!--descrive la composizione interna di un testo-->
				<derivation type="original"/>
				<domain type="education"/>
				<!--descrive il contesto sociale più importante in cui il testo è stato realizzato o al quale è destinato-->
				<factuality type="fact"/>
				<!--descrive la misura in cui il testo può essere considerato fantasioso o non fantasioso-->
				<interaction type="partial"
                    active="singular" passive="group"/>
				<!--descrive la natura di qualsiasi interazione tra coloro che producono e sperimentano il testo-->
				<preparedness type="draft"/>
				<!-- traduzione di draft = bozza, progetto-->
				<purpose type="inform" degree="high"/>
				<!--caratterizza un unico scopo o funzione comunicativa del testo-->
			</textDesc>
			<settingDesc>
				<setting>
					<name>
                        Testi registrati nella Biblioteca di 
                       
						<placeName>Ginevra</placeName>, 
					   
						<country>Svizzera</country>.
					
					</name>
					<time>
						<date when="1891-11">Novembre 1891</date>
					</time>
				</setting>
			</settingDesc>
		</profileDesc>
	</teiHeader>
	<facsimile>
		<!--contiene una rappresentazione di una fonte scritta sotto forma di un insieme di immagini-->
		<surface>
			<graphic url="pag8.png" xml:id="Pag8" width='2146px' height='1454px'/>
			<zone ulx="562" uly="33" lrx="1793" lry="1450" xml:id="FullPage8"/>
			<zone ulx="761" uly="90" lrx="1738" lry="150" xml:id="P8_R1"/>
			<zone ulx="770" uly="154" lrx="1746" lry="189" xml:id="P8_R2"/>
			<zone ulx="771" uly="198" lrx="1748" lry="236" xml:id="P8_R3"/>
			<zone ulx="778" uly="244" lrx="1765" lry="286" xml:id="P8_R4"/>
			<zone ulx="784" uly="297" lrx="1734" lry="330" xml:id="P8_R5"/>
			<zone ulx="768" uly="343" lrx="1784" lry="375" xml:id="P8_R6"/>
			<zone ulx="786" uly="401" lrx="1783" lry="426" xml:id="P8_R7"/>
			<zone ulx="774" uly="448" lrx="1745" lry="480" xml:id="P8_R8"/>
			<zone ulx="788" uly="500" lrx="1776" lry="538" xml:id="P8_R9"/>
			<zone ulx="784" uly="555" lrx="1750" lry="594" xml:id="P8_R10"/>
			<zone ulx="786" uly="612" lrx="1746" lry="651" xml:id="P8_R11"/>
			<zone ulx="617" uly="671" lrx="782"  lry="712" xml:id="P8_R12_Lat"/>
			<zone ulx="794" uly="669" lrx="1764" lry="713" xml:id="P8_R12"/>
			<zone ulx="774" uly="730" lrx="1709" lry="769" xml:id="P8_R13"/>
			<zone ulx="791" uly="789" lrx="1713" lry="818" xml:id="P8_R14"/>
			<zone ulx="790" uly="846" lrx="1734" lry="880" xml:id="P8_R15"/>
			<zone ulx="783" uly="910" lrx="1750" lry="935" xml:id="P8_R16"/>
			<zone ulx="794" uly="968" lrx="1735" lry="993" xml:id="P8_R17"/>
			<zone ulx="793" uly="1014" lrx="1720" lry="1048" xml:id="P8_R18"/>
			<zone ulx="798" uly="1084" lrx="1718" lry="1112" xml:id="P8_R19"/>
			<zone ulx="811" uly="1141" lrx="1721" lry="1168" xml:id="P8_R20"/>
			<zone ulx="816" uly="1188" lrx="1728" lry="1218" xml:id="P8_R21"/>
			<zone ulx="812" uly="1245" lrx="1765" lry="1283" xml:id="P8_R22"/>
			<zone ulx="816" uly="1298" lrx="1748" lry="1335" xml:id="P8_R23"/>
			<zone ulx="823" uly="1356" lrx="1758" lry="1386" xml:id="P8_R24"/>
			<zone ulx="1179" uly="1396" lrx="1736" lry="1411" xml:id="P8_R25"/>
			<zone ulx="1547" uly="1411" lrx="1788" lry="1434" xml:id="P8_R26"/>
		</surface>
		<surface>
			<graphic url="pag8R.png" xml:id="Pag8R" width='2146.007812px' height='1341.007812px'/>
			<zone ulx="539" uly="40" lrx="1691" lry="1314"/>
		</surface>
		<surface>
			<graphic url="pag9.png" xml:id="Pag9" width='2146px' height='1340px'/>
			<zone ulx="616" uly="16" lrx="1656" lry="1306" xml:id="FullPage9"/>
			<zone ulx="806" uly="39" lrx="1604" lry="100" xml:id="P9_R1"/>
			<zone ulx="808" uly="100" lrx="1617" lry="131" xml:id="P9_R2"/>
			<zone ulx="810" uly="133" lrx="1617" lry="161" xml:id="P9_R3"/>
			<zone ulx="810" uly="168" lrx="1640" lry="209" xml:id="P9_R4"/>
			<zone ulx="882" uly="214" lrx="1500" lry="245" xml:id="P9_R5"/>
			<zone ulx="880" uly="255" lrx="1610" lry="284" xml:id="P9_R6"/>
			<zone ulx="812" uly="301" lrx="1604" lry="327" xml:id="P9_R7"/>
